language: android

android:
    components:
      - tools
      - platform-tools
      - build-tools-23.0.3
      - android-23
      - extra-android-support
      - extra-android-m2repository
    licenses:
      - android-sdk-license-.+

script:
  - ./gradlew build

after_script:
  - cat app/build/outputs/lint-*debug.xml
  - cat app/build/reports/checkstyle/*.xml
